In [1]:
a = [1, 3, 5, 6]

In [2]:
a

[1, 3, 5, 6]

In [3]:
import numpy as np

In [9]:
re = np.zeros((1, 10))

In [10]:
re

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
re[0, a] = 1

In [17]:
re

array([[0., 1., 0., 1., 0., 1., 1., 0., 0., 0.]])

In [18]:
re[0]

array([0., 1., 0., 1., 0., 1., 1., 0., 0., 0.])